# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/zomato_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=f

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379